from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]
src += Glob('*.S')
group = DefineGroup('bootloader', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
